name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
  - cron: '5 11 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Fetch latest data
      run: |-
        # https://www.cdc.gov/flu/avianflu/data-map-wild-birds.html
        wget https://www.aphis.usda.gov/animal_health/data-csv/hpai-wild-birds.csv -O hpai-wild-birds.csv
        # https://www.cdc.gov/flu/avianflu/data-map-commercial.html
        wget https://www.cdc.gov/flu/avianflu/modules/commercial-backyard-flocks.csv -O commercial-backyard-flocks.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
